# Generated by Django 2.0.6 on 2018-10-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
