# Generated by Django 2.0.6 on 2018-10-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_auto_20181015_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
